# -*- coding: utf-8 -*-
"""Sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JNkOZpuIQuUG2efgGmWxtUn7dy82THDY

# **Sets(conjuntos**)

---

Tipo de dado iterável, imutável e sem elementos duplicados. Chamado de conjunto por possuir a mesma notação matemática dos conjuntos.

# **Exercícios**

---

1. Crie um algoritmo que pede ao usuário para digitar 3 números, diferentes entre sí, um de cada vez. A cada input do usuário insira o input dentro de um set e ao término printe na tela o output de seu set.
"""

sets = set()
n1=int(input("Digite um número: "))
n2=int(input("Digite um número diferente do anterior: "))
n3=int(input("Digite um número diferente dos anteriores: "))
sets.add(n1)
sets.add(n2)
sets.add(n3)
print(sets)

"""2. Crie um algoritmo que receba 3 números como input do usuário e a seguir adicione-o dentro de um frozenset. Ao término, aplique algum atributo frozenset e printe na tela. Utilize dir(frozenset) para selecionar o atributo."""

sets1 = set()
n1=int(input("Digite um número: "))
n2=int(input("Digite um número diferente do anterior: "))
n3=int(input("Digite um número diferente dos anteriores: "))
sets1.add(n1)
sets1.add(n2)
sets1.add(n3)
froz = frozenset(sets1)
print(froz)

# Obs.: Como o frozenset é imutável, para adicionar novos números é necessário convertê-lo para set.