# -*- coding: utf-8 -*-
"""TratamentoDeErrosEExceções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P-ujHfqH3LGmjEbGjjDM5yIErNgYteXu

# **>>> Tratando Erros e Exceções**

---

Erros vão acontecer e é importante que você os preveja e trate-os antes de sua aparição.

---

### **>>> Erros Comuns**
IOError: Se o arquivo não puder ser aberto/salvo.
<br>ImportError: Se o python não encontra o módulo
<br>ValueError: Operação recebe valor inadequado
<br>KeyboardInterrupt: Quando usuário clica DELETE ou CTRL+C
<br>EOFError: Quando o input não recebe nenhum dado
<br>TypeError: Erro de tipo para operação

## **>>> Resumindo...**

---

try: seu código;
<br>except: tratamento dos erros;
<br>else: tratamento com senão;
<br>finally: executa com ou sem exceções;

# **>>> Exercícios**

---

**1.** Crie um código em Python que solicite do usuário o input de um número inteiro. Caso haja preenchimento diferente, a máquina deve  guiar o usuário até ajustar sua resposta. (Fácil)
"""

while True:
  try:
    x = int(input("Digite um número inteiro: "))
    print(f"Você digitou {x}, parabéns!")
    break
  except ValueError:
    print("O valor digitado não é um inteiro. Tente novamente")

"""**2.** Crie um código em Python que solicite do usuário o input de 2 números inteiros e assim divida o primeiro número pelo segundo. Caso o input não seja um número inteiro, seu código deve guiar o usuário até o preenchimento correto. Caso o usuário preencha com 0,  que apresente mensagem falando sobre a indivisibilidade por zero. Caso o usuário não digite um número, informar que um número deve ser digitado. Em outros casos de erro, apresente ao usuário uma mensagem de erro inesperado.(Médio)"""

while True:
  try:
    x1 = int(input("Digite um número inteiro: "))
    x2= int(input("Digite outro número inteiro: "))
    div = x1/x2
    print(div)
    break
  except ValueError:
    print("O valor digitado não é um inteiro. Tente novamente") 
  except ZeroDivisionError:
      print( "Coloque um número diferente de zero" )
  except:
      print( "Tente novamente" )

"""**3.** Crie um código em Python que peça um número ímpar do usuário. Caso o número seja par, apresente mensagem guiando o usuário até o preenchimento correto(Difícil)"""

while True:
  try:
    x3 = int(input("Digite um número ímpar: "))
    if x3%2 == 0:
      print("Este é par")
    else:
      print("Parabéns!")
      break
  except ValueError:
    print("O valor digitado não é um inteiro. Tente novamente")